name: 'Maven Config for Pentaho'
description: 'A custom maven environment for Pentaho artifact builds'
inputs:
  args:
    description: 'The maven arguments'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    MAVEN_CONFIG: ${{ GITHUB_WORKSPACE }}/.m2 # to be able to cache dependencies
  args:
    - mvn
    - --batch-mode
    - --show-version
    - ${{ inputs.args }}
