name: Build

on:
  push:
    branches:
      - github-actions

jobs:
  test:
    name: Test wingman like
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cache Dependencies
        uses: actions/cache@v1
        with:
          path: .m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build
        uses: ./.github/actions/maven
        with:
          args: package -DskipTests

# Not working with cache enabled ??? getting permission denied
## [error]The template is not valid. Access to the path '/home/runner/work/pentaho-jenkins-shared-libraries/pentaho-jenkins-shared-libraries/.sonar/cache/b85e79af43c5fd9d871f67c00ce3c18d/sonar-java-plugin.jar_unzip' is denied.,Permission denied
# Also sonar cloud doesn't support groovy so is just a waist of time !
#      - name: SonarCloud Scan
#        uses: ./.github/actions/maven
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#        with:
#          args: sonar:sonar
