name: PR

on:
  pull_request:
    branches:
      - github-actions

jobs:
  test:
    name: Test wingman like
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cache Dependencies
        uses: actions/cache@v1
        with:
          path: .m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build
        uses: ./.github/actions/maven
        with:
          args: package

      - name: Comment PR
        uses: actions/github@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEBUG: true
          DEBUG_PAYLOAD: true
        with:
          args: comment "Hello from PR"